# Generated by Django 2.2 on 2019-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
